// user
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const LOG_ERROR = 'LOG_ERROR'
export const LOG_START = 'LOG_START'
export const LOG_FRONT_OUT = 'LOG_FRONT_OUT'

export const GET_ENUM = 'GET_ENUM'

// 图片上传
export const SET_UPLOADIMG = 'SET_UPLOADIMG'
export const REMOVE_UPLOADIMG = 'REMOVE_UPLOADIMG'

// 添加记账
export const SET_BOOKKEEP = 'SET_BOOKKEEP'
export const REMOVE_BOOKKEEP = 'REMOVE_BOOKKEEP'

// 应用更新
export const SET_UPDATE_PROGRESS = 'SET_UPDATE_PROGRESS'
export const SET_UPDATE_STATUS = 'INSERT_APPROVALLIST'

// 审批列表
export const SET_APPROVALLIST = 'SET_APPROVALLIST'
export const UPDATE_APPROVALLIST = 'UPDATE_APPROVALLIST'
export const CLEAR_APPROVALLIST = 'CLEAR_APPROVALLIST'

// 合同详情
export const SET_CONTRACTDETAIL = 'SET_CONTRACTDATA'
export const UPDATE_CONTRACTDETAIL = 'UPDATE_CONTRACTDETAIL'
// 合同列表
export const SET_CONTRACTLIST = 'SET_CONTRACTLIST'
export const UPDATE_CONTRACTLIST = 'UPDATE_CONTRACTLIST'
export const DELETE_CONTRACTLIST = 'DELETE_CONTRACTLIST'
// 预定详情
export const SET_ORDERDETAIL = 'SET_ORDERDETAIL'
export const UPDATE_ORDERDETAIL = 'UPDATE_ORDERDETAIL'
export const DELETE_ORDERDETAIL = 'DELETE_ORDERDETAIL'
// 待收账单列表
export const SET_WAITCOLLECTBILLLIST = 'SET_WAITCOLLECTBILLLIST'
export const REMOVE_WAITCOLLECTBILLLIST = 'REMOVE_WAITCOLLECTBILLLIST'
export const CLEAR_WAITCOLLECTBILLLIST = 'CLEAR_WAITCOLLECTBILLLIST'
export const UPDATE_WAITCOLLECTBILLLIST = 'UPDATE_WAITCOLLECTBILLLIST'
// 资源
export const SET_OWNER_RESOURCELIST = 'SET_OWNER_RESOURCELIST'
export const CLEAR_OWNER_RESOURCELIST = 'CLEAR_OWNER_RESOURCELIST'
export const ADD_OWNER_RESOURCE = 'ADD_OWNER_RESOURCE'
export const UPDATE_OWNER_RESOURCE = 'UPDATE_OWNER_RESOURCE'
export const DELETE_GUEST = 'DELETE_GUEST'
export const SET_FOLLOWLIST = 'SET_FOLLOWLIST'
export const ADD_FOLLOW_DETAIL = 'ADD_FOLLOW_DETAIL'
export const CLEAR_FOLLOWLIST = 'CLEAR_FOLLOWLIST'
// 报修列表
export const UPDATE_REPAIRLIST = 'UPDATE_REPAIRLIST'
export const SET_REPAIRLIST = 'SET_REPAIRLIST'
export const REMOVE_REPAIRLIST = 'REMOVE_REPAIRLIST'
export const REMOVE_PAYRECEIVELIST_ITEM = 'REMOVE_PAYRECEIVELIST_ITEM'
// 收付款列表
export const UPDATE_PAYRECEIVELIST = 'UPDATE_PAYRECEIVELIST'
export const SET_PAYRECEIVELIST = 'SET_PAYRECEIVELIST'
export const REMOVE_PAYRECEIVELIST = 'REMOVE_PAYRECEIVELIST'

// 列表
export const SETLIST = 'SETLIST'
export const UPDATELIST = 'UPDATELIST'
export const DELETELIST = 'DELETELIST'
export const ADDLIST = 'ADDLIST'

// 账号
export const ACCOUNTLIST = 'ACCOUNTLIST'
// 记账详情
export const SET_ACCOUNTDETAIL = 'SET_ACCOUNTDETAIL'
// 记账详情修改
export const UPDATE_ACCOUNTDETAIL = 'UPDATE_ACCOUNTDETAIL'

//装修详情
export const SET_RENOVATIONDETAIL = 'SET_RENOVATIONDETAIL'
//装修详情修改
export const UPDATE_RENOVATIONDETAIL = 'UPDATE_RENOVATIONDETAIL'

//搬家详情
export const SET_MOVINGDETAIL = 'SET_MOVINGDETAIL'
//搬家详情修改
export const UPDATE_MOVINGDETAIL = 'UPDATE_MOVINGDETAIL'